#!/usr/bin/env python3
"""Generate the rulebook POLICY_INDEX files from the shipped rule pack.

The index/appendix is a pure projection of `trustabl-rules` — regenerating it
from the YAML is the only way to keep it from drifting (the hand-maintained
index had gone stale at 43 rules while 64 shipped). This writes:

  * POLICY_INDEX.md                  — the master index (totals + all rules)
  * <category>/POLICY_INDEX.md       — one per-SDK index

Risk score = severity_weight × confidence × 100, where the weights are the
engine's (internal/models.SeverityWeight): critical 1.0, high 0.7, medium 0.4,
low 0.15, info 0.05. Rounded to one decimal, round-half-up.

Usage:
    python tools/gen_index.py [--rules-repo PATH]   # write the files
    python tools/gen_index.py --check               # CI: fail if regen would change anything

Exit: 0 = wrote / up-to-date; 1 = --check found drift; 2 = rules repo missing.
"""

from __future__ import annotations

import argparse
import os
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from check_rulebook import RuleSpec, load_rules

GH_BASE = "https://github.com/trustabl/trustabl-rules/blob/main/"
GENERATED_MARKER = "<!-- Generated by tools/gen_index.py. Do not edit by hand. -->"

SDK_ORDER = ["claude_sdk", "openai_sdk", "google_adk", "mcp"]
SDK_LABEL = {"claude_sdk": "Claude SDK", "openai_sdk": "OpenAI SDK", "google_adk": "Google ADK", "mcp": "MCP"}
SDK_FULL = {
    "claude_sdk": "Claude Agent SDK",
    "openai_sdk": "OpenAI Agents SDK",
    "google_adk": "Google ADK",
    "mcp": "Model Context Protocol",
}
SCOPE_ORDER = ["tool", "agent", "subagent", "repo"]

SEVERITY_WEIGHT = {
    "critical": Decimal("1.0"),
    "high": Decimal("0.7"),
    "medium": Decimal("0.4"),
    "low": Decimal("0.15"),
    "info": Decimal("0.05"),
}

RISK_FORMULA_LINE = (
    "Risk score = `severity_weight × confidence × 100` (engine formula; weights: "
    "low=0.15, medium=0.40, high=0.70). Higher = worse."
)

MASTER_PREAMBLE = """# Policy index

All shipped rules across every SDK. ID prefix denotes the rule family:
`CSDK-` Claude Agent SDK, `OAI-` OpenAI Agents SDK, `ADK-` Google ADK,
`MCP-` Model Context Protocol. Within a family: `NNN` tool-scope, `1NN`
agent / subagent scope, `2NN` repo scope.

{risk}

## Contributing a new policy

Every policy in this index has a paired rationale doc following the same
authoring template. The template lives at
[docs/policy-rationale-doc-template-guide.md](docs/policy-rationale-doc-template-guide.md)
and defines the rationale doc at `docs/Policy/<category>/<topic>.md` and its
required sections (threat model, detection mechanics, references). The
authoritative rule YAML schema lives in the engine
([internal/rules/schema.yaml](https://github.com/trustabl/trustabl/blob/main/internal/rules/schema.yaml)).
Users can contribute their own policies by:

1. Reading the rule-authoring contract in
   [trustabl-rules/CLAUDE.md](https://github.com/trustabl/trustabl-rules/blob/main/CLAUDE.md)
   (required fields, per-scope `applies_to` values, ID conventions, severity
   guidance).
2. Adding the YAML rule to the
   [trustabl-rules](https://github.com/trustabl/trustabl-rules) repo under
   `<sdk_category>/<topic>.yaml` — that is the pack the engine loads.
3. Copying the template from
   [docs/policy-rationale-doc-template-guide.md](docs/policy-rationale-doc-template-guide.md),
   filling every section, and adding the paired rationale **here** at
   `docs/Policy/<sdk_category>/<topic>.md`.
4. Mirroring the rule into the engine repo's `testdata/rules-fixture/` with at
   least one fire case and one silent case (see the engine's
   `testdata/rules-fixture/CLAUDE.md`, "Add a rule for X").
5. Opening the PRs — the rule appears here once the rulebook PR merges.
""".format(risk=RISK_FORMULA_LINE)


def numeric_id(rule_id: str) -> int:
    try:
        return int(rule_id.split("-", 1)[1])
    except (IndexError, ValueError):
        return 0


def sort_key(r: RuleSpec) -> tuple[int, int, str]:
    cat_rank = SDK_ORDER.index(r.category) if r.category in SDK_ORDER else len(SDK_ORDER)
    return (cat_rank, numeric_id(r.rule_id), r.rule_id)


def risk_score(severity: str, confidence: float) -> str:
    weight = SEVERITY_WEIGHT.get(severity, SEVERITY_WEIGHT["info"])
    val = (weight * Decimal(str(confidence)) * 100).quantize(
        Decimal("0.1"), rounding=ROUND_HALF_UP
    )
    return f"{val}"


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a GitHub markdown table with per-column padding (deterministic)."""
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))

    def fmt(cells: list[str]) -> str:
        return "| " + " | ".join(c.ljust(widths[i]) for i, c in enumerate(cells)) + " |"

    sep = "| " + " | ".join("-" * widths[i] for i in range(len(headers))) + " |"
    lines = [fmt(headers), sep]
    lines.extend(fmt(r) for r in rows)
    return "\n".join(lines)


def rule_row(n: int, r: RuleSpec, source_label: str) -> list[str]:
    src = f"[{source_label}]({GH_BASE}{r.source})"
    return [
        str(n),
        r.rule_id,
        SDK_LABEL.get(r.category, r.category),
        r.scope,
        ", ".join(r.applies_to),
        r.title,
        r.severity,
        f"{r.confidence:.2f}",
        risk_score(r.severity, r.confidence),
        src,
    ]


HEADERS = ["", "Id", "SDK/ADK", "Scope", "Applies To", "Policy", "Severity", "Confidence", "Risk", "Source"]


def scope_breakdown(rules: list[RuleSpec]) -> dict[str, int]:
    counts = {s: 0 for s in SCOPE_ORDER}
    for r in rules:
        counts[r.scope] = counts.get(r.scope, 0) + 1
    return counts


def build_master(rules: list[RuleSpec]) -> str:
    by_cat: dict[str, list[RuleSpec]] = {c: [] for c in SDK_ORDER}
    for r in rules:
        by_cat.setdefault(r.category, []).append(r)

    # Totals table
    totals_headers = ["SDK", "Tool", "Agent", "Subagent", "Repo", "Total", "Per-SDK index"]
    totals_rows: list[list[str]] = []
    grand = {s: 0 for s in SCOPE_ORDER}
    grand_total = 0
    for cat in SDK_ORDER:
        cr = by_cat.get(cat, [])
        b = scope_breakdown(cr)
        for s in SCOPE_ORDER:
            grand[s] += b[s]
        grand_total += len(cr)
        link = f"[{cat}/POLICY_INDEX.md]({cat}/POLICY_INDEX.md)"
        totals_rows.append(
            [SDK_FULL[cat], str(b["tool"]), str(b["agent"]), str(b["subagent"]),
             str(b["repo"]), str(len(cr)), link]
        )
    totals_rows.append(
        ["**All**", f"**{grand['tool']}**", f"**{grand['agent']}**",
         f"**{grand['subagent']}**", f"**{grand['repo']}**", f"**{grand_total}**", ""]
    )
    totals = render_table(totals_headers, totals_rows)

    # All-rules table
    ordered = sorted(rules, key=sort_key)
    rows = [rule_row(i + 1, r, f"{r.category}/{r.topic}.yaml") for i, r in enumerate(ordered)]
    all_rules = render_table(HEADERS, rows)

    return (
        f"{GENERATED_MARKER}\n{MASTER_PREAMBLE}\n"
        f"## Totals\n\n{totals}\n\n"
        f"## All rules\n\n{all_rules}\n"
    )


def build_per_sdk(cat: str, rules: list[RuleSpec]) -> str:
    cr = sorted([r for r in rules if r.category == cat], key=sort_key)
    b = scope_breakdown(cr)
    parts = [f"{b[s]} {s}" for s in SCOPE_ORDER if b[s]]
    breakdown = " · ".join(parts)
    rows = [rule_row(i + 1, r, f"{r.topic}.yaml") for i, r in enumerate(cr)]
    table = render_table(HEADERS, rows)
    return (
        f"{GENERATED_MARKER}\n"
        f"# {SDK_FULL[cat]} policy index\n\n"
        f"{len(cr)} rules — {breakdown}\n\n"
        f"{RISK_FORMULA_LINE}\n\n"
        f"{table}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate rulebook POLICY_INDEX files.")
    default_rules = os.environ.get("TRUSTABL_RULES_REPO", "../trustabl-rules")
    ap.add_argument("--rules-repo", default=default_rules)
    ap.add_argument("--check", action="store_true", help="fail if regeneration would change a file")
    args = ap.parse_args()

    rulebook_repo = Path(__file__).resolve().parent.parent
    rules_repo = Path(args.rules_repo)
    if not rules_repo.is_absolute():
        rules_repo = (rulebook_repo / rules_repo).resolve()
    if not rules_repo.is_dir():
        print(f"error: rules repo not found: {rules_repo}", file=sys.stderr)
        return 2

    rules_map, load_errors = load_rules(rules_repo)
    if load_errors:
        for e in load_errors:
            print(f"ERROR {e}", file=sys.stderr)
        return 2
    rules = list(rules_map.values())

    targets: dict[Path, str] = {rulebook_repo / "POLICY_INDEX.md": build_master(rules)}
    for cat in SDK_ORDER:
        targets[rulebook_repo / cat / "POLICY_INDEX.md"] = build_per_sdk(cat, rules)

    drift = []
    for path, content in targets.items():
        rel = path.relative_to(rulebook_repo).as_posix()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != content:
                drift.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {rel}")

    if args.check:
        if drift:
            print("STALE index files (run `python tools/gen_index.py`):")
            for d in drift:
                print(f"  {d}")
            return 1
        print(f"OK: {len(targets)} index file(s) up to date ({len(rules)} rules).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
